const questions = [
	{
		tag: "cf-robot-message",
		"cf-questions": "You have 10 Minutes to answer 20 question.",
	},
	{
		tag: "cf-robot-message",
		"cf-questions": "Your time starts when you answer your first question",
	},
	{
		tag: "fieldset",
		type: "Checkboxes buttons",
		id: "question1",
		"cf-input-placeholder": "Choose one of the above",
		"cf-questions":
			"A carton of Dangote sugar contains 40 sachets. If each carton costs 4,000. How much is one sachet of Dangote Sugar?",
		children: [
			{
				tag: "input",
				type: "radio",
				required: "required",
				value: "1",
				name: "question1",
				"cf-label": "120",
			},
			{
				tag: "input",
				type: "radio",
				required: "required",
				value: "2",
				name: "question1",
				"cf-label": "80",
			},
			{
				tag: "input",
				type: "radio",
				required: "required",
				value: "3",
				name: "question1",
				"cf-label": "100",
			},
			{
				tag: "input",
				type: "radio",
				required: "required",
				value: "4",
				name: "question1",
				"cf-label": "150",
			},
		],
	},

	//////2
	{
		tag: "fieldset",
		type: "Checkboxes buttons",
		id: "question1",
		name: "question2",
		"cf-input-placeholder": "Choose one of the above",
		"cf-questions":
			"Sandra’s monthly sales target is 5 million naira. At the end of January, she sold 3.5 million naira. What is Sandra's % sales achievement in January?",
		children: [
			{
				tag: "input",
				type: "radio",
				required: "required",
				value: "1",
				name: "question2",
				"cf-label": "30%",
			},
			{
				tag: "input",
				type: "radio",
				required: "required",
				value: "2",
				name: "question2",
				"cf-label": "35%",
			},
			{
				tag: "input",
				type: "radio",
				required: "required",
				value: "3",
				name: "question2",
				"cf-label": "50%",
			},
			{
				tag: "input",
				type: "radio",
				required: "required",
				value: "4",
				name: "question2",
				"cf-label": "70%",
			},
		],
	},
	////////2
	{
		tag: "fieldset",
		type: "Checkboxes buttons",
		id: "question1",
		"cf-input-placeholder": "Choose one of the above",
		"cf-questions":
			"Mahmud has a total of 120 customers in IBB market, Suleja. Last week, he sold to only 30 of them. What was Mahmud's sales productivity last week?",
		children: [
			{
				tag: "input",
				type: "radio",
				required: "required",
				value: "1",
				name: "question3",
				"cf-label": "40%",
			},
			{
				tag: "input",
				type: "radio",
				required: "required",
				value: "2",
				name: "question3",
				"cf-label": "25%",
			},
			{
				tag: "input",
				type: "radio",
				required: "required",
				value: "3",
				name: "question3",
				"cf-label": "30%",
			},
			{
				tag: "input",
				type: "radio",
				required: "required",
				value: "4",
				name: "question3",
				"cf-label": "10%",
			},
		],
	},
	/////////
	{
		tag: "fieldset",
		type: "Checkboxes buttons",
		id: "question1",
		name: "question2",
		"cf-input-placeholder": "Choose one of the above",
		"cf-questions":
			"Peju sold 25 cartons of Gino Pepper & Onion 70g to Alhaja Ola. If each carton cost 3,750 naira, how much will Peju collect from Alhaja Ola?",
		children: [
			{
				tag: "input",
				type: "radio",
				required: "required",
				value: "1",
				name: "question4",
				"cf-label": "30%",
			},
			{
				tag: "input",
				type: "radio",
				required: "required",
				value: "2",
				name: "question4",
				"cf-label": "35%",
			},
			{
				tag: "input",
				type: "radio",
				required: "required",
				value: "3",
				name: "question4",
				"cf-label": "50%",
			},
			{
				tag: "input",
				type: "radio",
				required: "required",
				value: "4",
				name: "question4",
				"cf-label": "70%",
			},
		],
	},
	//////////
	{
		tag: "fieldset",
		type: "Checkboxes buttons",
		"cf-questions":
			"Which of the following is NOT a product you'll find in retail food stores?",
		children: [
			{
				tag: "input",
				type: "radio",
				required: "required",
				value: "1",
				name: "question5",
				"cf-label": "Golden Penny Spaghetti",
			},
			{
				tag: "input",
				type: "radio",
				required: "required",
				value: "2",
				name: "question5",
				"cf-label": "Gino Tomato Paste",
			},
			{
				tag: "input",
				type: "radio",
				required: "required",
				value: "3",
				name: "question5",
				"cf-label": "Indomie Instant Noodles",
			},
			{
				tag: "input",
				type: "radio",
				required: "required",
				value: "4",
				name: "question5",
				"cf-label": "None of the above",
			},
		],
	},
	///////////
	{
		tag: "fieldset",
		type: "Checkboxes buttons",
		id: "question7",
		"cf-input-placeholder": "Choose one of the above",
		"cf-questions":
			"Joseph visits 25 customers per day. If he works 6 days a week, how many visits does Joseph make per week?",
		children: [
			{
				tag: "input",
				type: "radio",
				required: "required",
				value: "1",
				name: "question7",
				"cf-label": "25",
			},
			{
				tag: "input",
				type: "radio",
				required: "required",
				value: "2",
				name: "question7",
				"cf-label": "31",
			},
			{
				tag: "input",
				type: "radio",
				required: "required",
				value: "3",
				name: "question7",
				"cf-label": "150",
			},
			{
				tag: "input",
				type: "radio",
				required: "required",
				value: "4",
				name: "question7",
				"cf-label": "100",
			},
		],
	},
	{
		tag: "fieldset",
		type: "Checkboxes buttons",
		id: "question8",
		"cf-input-placeholder": "Choose one of the above",
		"cf-questions": "Which of these does not belong to the group?",
		children: [
			{
				tag: "input",
				type: "radio",
				required: "required",
				value: "1",
				name: "question8",
				"cf-label": "Gino Max",
			},
			{
				tag: "input",
				type: "radio",
				required: "required",
				value: "2",
				name: "question8",
				"cf-label": "Pepsi",
			},
			{
				tag: "input",
				type: "radio",
				required: "required",
				value: "3",
				name: "question8",
				"cf-label": "Knorr",
			},
			{
				tag: "input",
				type: "radio",
				required: "required",
				value: "4",
				name: "question8",
				"cf-label": "Maggi",
			},
		],
	},
	{
		tag: "fieldset",
		type: "Checkboxes buttons",
		id: "question9",
		"cf-input-placeholder": "Choose one of the above",
		"cf-questions":
			"Which of these stores may likely NOT sell Tasty Tom seasoning cubes?",
		children: [
			{
				tag: "input",
				type: "radio",
				required: "required",
				value: "1",
				name: "question9",
				"cf-label": "Food Store",
			},
			{
				tag: "input",
				type: "radio",
				required: "required",
				value: "2",
				name: "question9",
				"cf-label": "Provisions Store",
			},
			{
				tag: "input",
				type: "radio",
				required: "required",
				value: "3",
				name: "question9",
				"cf-label": "Supermarket",
			},
			{
				tag: "input",
				type: "radio",
				required: "required",
				value: "4",
				name: "question9",
				"cf-label": "Pharmacy Store",
			},
		],
	},
	{
		tag: "fieldset",
		type: "Checkboxes buttons",
		id: "question10",
		"cf-input-placeholder": "Choose one of the above",
		"cf-questions": "Which of these is a State capital in Nigeria?",
		children: [
			{
				tag: "input",
				type: "radio",
				required: "required",
				value: "1",
				name: "question10",
				"cf-label": "Delta",
			},
			{
				tag: "input",
				type: "radio",
				required: "required",
				value: "2",
				name: "question10",
				"cf-label": "Jigawa",
			},
			{
				tag: "input",
				type: "radio",
				required: "required",
				value: "3",
				name: "question10",
				"cf-label": "Oyo",
			},
			{
				tag: "input",
				type: "radio",
				required: "required",
				value: "4",
				name: "question10",
				"cf-label": "Enugu",
			},
		],
	},
	{
		tag: "fieldset",
		type: "Checkboxes buttons",
		id: "question11",
		"cf-input-placeholder": "Choose one of the above",
		"cf-questions": "A Kiosk is bigger than a Supermarket.",
		children: [
			{
				tag: "input",
				type: "radio",
				required: "required",
				value: "1",
				name: "question11",
				"cf-label": "True",
			},
			{
				tag: "input",
				type: "radio",
				required: "required",
				value: "2",
				name: "question11",
				"cf-label": "False",
			},
		],
	},
	{
		tag: "fieldset",
		type: "Checkboxes buttons",
		id: "question12",
		"cf-input-placeholder": "Choose one of the above",
		"cf-questions": `Procter & Gamble is running a "Buy 10 get 1 free" on Oral-B. Mama Aisha bought 50 cartons. What is the value of the free products she'll get if each carton cost 4,000 naira?`,
		children: [
			{
				tag: "input",
				type: "radio",
				required: "required",
				value: "1",
				name: "question12",
				"cf-label": "40,000",
			},
			{
				tag: "input",
				type: "radio",
				required: "required",
				value: "2",
				name: "question12",
				"cf-label": "20,000",
			},
			{
				tag: "input",
				type: "radio",
				required: "required",
				value: "3",
				name: "question12",
				"cf-label": "55,000",
			},
			{
				tag: "input",
				type: "radio",
				required: "required",
				value: "4",
				name: "question12",
				"cf-label": "200,000",
			},
		],
	},
	{
		tag: "fieldset",
		type: "Checkboxes buttons",
		id: "question13",
		"cf-input-placeholder": "Choose one of the above",
		"cf-questions": "Tecno is a brand of mobile phone.",
		children: [
			{
				tag: "input",
				type: "radio",
				required: "required",
				value: "1",
				name: "question13",
				"cf-label": "True",
			},
			{
				tag: "input",
				type: "radio",
				required: "required",
				value: "2",
				name: "question13",
				"cf-label": "False",
			},
		],
	},
	{
		tag: "fieldset",
		type: "Checkboxes buttons",
		id: "question14",
		"cf-input-placeholder": "Choose one of the above",
		"cf-questions":
			"Uche bought 8 packs of Jago mayonnaise for 15,000 naira each. He resells each pack at 15,450 naira. What was his total profit on the Jago packs?",
		children: [
			{
				tag: "input",
				type: "radio",
				required: "required",
				value: "1",
				name: "question14",
				"cf-label": "450",
			},
			{
				tag: "input",
				type: "radio",
				required: "required",
				value: "2",
				name: "question14",
				"cf-label": "15,450",
			},
			{
				tag: "input",
				type: "radio",
				required: "required",
				value: "3",
				name: "question14",
				"cf-label": "3,600",
			},
			{
				tag: "input",
				type: "radio",
				required: "required",
				value: "4",
				name: "question14",
				"cf-label": "6,300",
			},
		],
	},
	{
		tag: "fieldset",
		type: "Checkboxes buttons",
		id: "question15",
		"cf-input-placeholder": "Choose one of the above",
		"cf-questions":
			"A carton of Gino Max Chicken contains 40 sachets of cubes. Mama Nkechi bought 2 cartons for N3,800 each. If she sells each sachet for N100, how much profit did she make?",
		children: [
			{
				tag: "input",
				type: "radio",
				required: "required",
				value: "1",
				name: "question15",
				"cf-label": "N400",
			},
			{
				tag: "input",
				type: "radio",
				required: "required",
				value: "2",
				name: "question15",
				"cf-label": "N500",
			},
			{
				tag: "input",
				type: "radio",
				required: "required",
				value: "3",
				name: "question15",
				"cf-label": "N1,500",
			},
			{
				tag: "input",
				type: "radio",
				required: "required",
				value: "4",
				name: "question15",
				"cf-label": "N200",
			},
		],
	},
	{
		tag: "fieldset",
		type: "Checkboxes buttons",
		id: "question16",
		"cf-input-placeholder": "Choose one of the above",
		"cf-questions": "Food = Eat; Water = ?",
		children: [
			{
				tag: "input",
				type: "radio",
				required: "required",
				value: "1",
				name: "question16",
				"cf-label": "Swallow",
			},
			{
				tag: "input",
				type: "radio",
				required: "required",
				value: "2",
				name: "question16",
				"cf-label": "Chew",
			},
			{
				tag: "input",
				type: "radio",
				required: "required",
				value: "3",
				name: "question16",
				"cf-label": "Drink",
			},
			{
				tag: "input",
				type: "radio",
				required: "required",
				value: "4",
				name: "question16",
				"cf-label": "Munch",
			},
		],
	},
	{
		tag: "fieldset",
		type: "Checkboxes buttons",
		id: "question17",
		"cf-input-placeholder": "Choose one of the above",
		"cf-questions":
			"Research shows that one store serves approximately 300 people in Lagos. How any stores are in an Estate community of 6,000 people?",
		children: [
			{
				tag: "input",
				type: "radio",
				required: "required",
				value: "1",
				name: "question17",
				"cf-label": "10",
			},
			{
				tag: "input",
				type: "radio",
				required: "required",
				value: "2",
				name: "question17",
				"cf-label": "20",
			},
			{
				tag: "input",
				type: "radio",
				required: "required",
				value: "3",
				name: "question17",
				"cf-label": "300",
			},
			{
				tag: "input",
				type: "radio",
				required: "required",
				value: "4",
				name: "question17",
				"cf-label": "6,000",
			},
		],
	},
	{
		tag: "fieldset",
		type: "Checkboxes buttons",
		id: "question18",
		"cf-input-placeholder": "Choose one of the above",
		"cf-questions": "He and I ______ at UNIJOS together.",
		children: [
			{
				tag: "input",
				type: "radio",
				required: "required",
				value: "1",
				name: "question18",
				"cf-label": "were",
			},
			{
				tag: "input",
				type: "radio",
				required: "required",
				value: "2",
				name: "question18",
				"cf-label": "was",
			},
			{
				tag: "input",
				type: "radio",
				required: "required",
				value: "3",
				name: "question18",
				"cf-label": "is",
			},
			{
				tag: "input",
				type: "radio",
				required: "required",
				value: "4",
				name: "question18",
				"cf-label": "are",
			},
		],
	},
	{
		tag: "fieldset",
		type: "Checkboxes buttons",
		id: "question19",
		"cf-input-placeholder": "Choose one of the above",
		"cf-questions": "Butterfly to Caterpillar : Toad to",
		children: [
			{
				tag: "input",
				type: "radio",
				required: "required",
				value: "1",
				name: "question19",
				"cf-label": "Frog",
			},
			{
				tag: "input",
				type: "radio",
				required: "required",
				value: "2",
				name: "question19",
				"cf-label": "Worm",
			},
			{
				tag: "input",
				type: "radio",
				required: "required",
				value: "3",
				name: "question19",
				"cf-label": "Tadpole",
			},
			{
				tag: "input",
				type: "radio",
				required: "required",
				value: "4",
				name: "question19",
				"cf-label": "Spider",
			},
		],
	},
	{
		tag: "fieldset",
		type: "Checkboxes buttons",
		id: "question20",
		"cf-input-placeholder": "Choose one of the above",
		"cf-questions": "Each of the boys ______ given a present.",
		children: [
			{
				tag: "input",
				type: "radio",
				required: "required",
				value: "1",
				name: "question20",
				"cf-label": "was",
			},
			{
				tag: "input",
				type: "radio",
				required: "required",
				value: "2",
				name: "question20",
				"cf-label": "were",
			},
			{
				tag: "input",
				type: "radio",
				required: "required",
				value: "3",
				name: "question20",
				"cf-label": "are",
			},
			{
				tag: "input",
				type: "radio",
				required: "required",
				value: "4",
				name: "question20",
				"cf-label": "will have been",
			},
		],
	},
	{
		tag: "fieldset",
		type: "Checkboxes buttons",
		id: "question21",
		"cf-input-placeholder": "Choose one of the above",
		"cf-questions": "How many local government areas are in Nigeria?",
		children: [
			{
				tag: "input",
				type: "radio",
				required: "required",
				value: "1",
				name: "question21",
				"cf-label": "36",
			},
			{
				tag: "input",
				type: "radio",
				required: "required",
				value: "2",
				name: "question21",
				"cf-label": "774",
			},
			{
				tag: "input",
				type: "radio",
				required: "required",
				value: "3",
				name: "question21",
				"cf-label": "109",
			},
			{
				tag: "input",
				type: "radio",
				required: "required",
				value: "4",
				name: "question21",
				"cf-label": "360",
			},
		],
	},
	{
		tag: "fieldset",
		type: "Checkboxes buttons",
		id: "question21",
		"cf-input-placeholder": "Choose one of the above",
		"cf-questions": "What does the term FMCG stands for in retail?",
		children: [
			{
				tag: "input",
				type: "radio",
				required: "required",
				value: "1",
				name: "question22",
				"cf-label": "Federal Ministry of Commerce and Governance",
			},
			{
				tag: "input",
				type: "radio",
				required: "required",
				value: "2",
				name: "question22",
				"cf-label": "Future Market Customer Groups",
			},
			{
				tag: "input",
				type: "radio",
				required: "required",
				value: "3",
				name: "question22",
				"cf-label": "Fast Moving Consumer Goods",
			},
			{
				tag: "input",
				type: "radio",
				required: "required",
				value: "4",
				name: "question22",
				"cf-label": "None of the above",
			},
		],
	},
	{
		tag: "fieldset",
		type: "Checkboxes buttons",
		id: "question23",
		"cf-input-placeholder": "Choose one of the above",
		"cf-questions": "In Nigeria, Democracy Day is now celebrated on?",
		children: [
			{
				tag: "input",
				type: "radio",
				required: "required",
				value: "1",
				name: "question23",
				"cf-label": "May 27th",
			},
			{
				tag: "input",
				type: "radio",
				required: "required",
				value: "2",
				name: "question23",
				"cf-label": "October 1st",
			},
			{
				tag: "input",
				type: "radio",
				required: "required",
				value: "3",
				name: "question23",
				"cf-label": "June 12th",
			},
			{
				tag: "input",
				type: "radio",
				required: "required",
				value: "4",
				name: "question23",
				"cf-label": "January 1st",
			},
		],
	},
	{
		tag: "fieldset",
		type: "Checkboxes buttons",
		id: "question24",
		"cf-input-placeholder": "Choose one of the above",
		"cf-questions":
			" Who is the current Governor of the Central Bank of Nigeria?",
		children: [
			{
				tag: "input",
				type: "radio",
				required: "required",
				value: "1",
				name: "question24",
				"cf-label": "Charles Soludo",
			},
			{
				tag: "input",
				type: "radio",
				required: "required",
				value: "2",
				name: "question24",
				"cf-label": "Godwin Emefiele",
			},
			{
				tag: "input",
				type: "radio",
				required: "required",
				value: "3",
				name: "question24",
				"cf-label": "Nasir El-Rufai",
			},
			{
				tag: "input",
				type: "radio",
				required: "required",
				value: "4",
				name: "question24",
				"cf-label": "Attahiru Jega",
			},
		],
	},
	{
		tag: "fieldset",
		type: "Checkboxes buttons",
		id: "question25",
		"cf-input-placeholder": "Choose one of the above",
		"cf-questions":
			"Which is the largest city in Nigeria in terms of population?",
		children: [
			{
				tag: "input",
				type: "radio",
				required: "required",
				value: "1",
				name: "question25",
				"cf-label": "Ibadan",
			},
			{
				tag: "input",
				type: "radio",
				required: "required",
				value: "2",
				name: "question25",
				"cf-label": "Kano",
			},
			{
				tag: "input",
				type: "radio",
				required: "required",
				value: "3",
				name: "question25",
				"cf-label": "Lagos",
			},
			{
				tag: "input",
				type: "radio",
				required: "required",
				value: "4",
				name: "question25",
				"cf-label": "Enugu",
			},
		],
	},

	{
		tag: "fieldset",
		type: "Checkboxes buttons",
		id: "question26",
		"cf-input-placeholder": "Choose one of the above",
		"cf-questions": "Pick the odd one?",
		children: [
			{
				tag: "input",
				type: "radio",
				required: "required",
				value: "1",
				name: "question26",
				"cf-label": "Spaghetti",
			},
			{
				tag: "input",
				type: "radio",
				required: "required",
				value: "2",
				name: "question26",
				"cf-label": "Spaghettini",
			},
			{
				tag: "input",
				type: "radio",
				required: "required",
				value: "3",
				name: "question26",
				"cf-label": "Macaroni",
			},
			{
				tag: "input",
				type: "radio",
				required: "required",
				value: "4",
				name: "question26",
				"cf-label": "Semovita",
			},
		],
	},

	{
		tag: "fieldset",
		type: "Checkboxes buttons",
		id: "question26",
		"cf-input-placeholder": "Choose one of the above",
		"cf-questions": "Pick the odd one?",
		children: [
			{
				tag: "input",
				type: "radio",
				required: "required",
				value: "1",
				name: "question26",
				"cf-label": "Spaghetti",
			},
			{
				tag: "input",
				type: "radio",
				required: "required",
				value: "2",
				name: "question26",
				"cf-label": "Spaghettini",
			},
			{
				tag: "input",
				type: "radio",
				required: "required",
				value: "3",
				name: "question26",
				"cf-label": "Macaroni",
			},
			{
				tag: "input",
				type: "radio",
				required: "required",
				value: "4",
				name: "question26",
				"cf-label": "Semovita",
			},
		],
	},
	{
		tag: "fieldset",
		type: "Checkboxes buttons",
		id: "question27",
		"cf-input-placeholder": "Choose one of the above",
		"cf-questions": "5% of 1,000 is?",
		children: [
			{
				tag: "input",
				type: "radio",
				required: "required",
				value: "1",
				name: "question27",
				"cf-label": "5,000",
			},
			{
				tag: "input",
				type: "radio",
				required: "required",
				value: "2",
				name: "question27",
				"cf-label": "50",
			},
			{
				tag: "input",
				type: "radio",
				required: "required",
				value: "3",
				name: "question27",
				"cf-label": "5",
			},
			{
				tag: "input",
				type: "radio",
				required: "required",
				value: "4",
				name: "question27",
				"cf-label": "0.5",
			},
		],
	},

	{
		tag: "fieldset",
		type: "Checkboxes buttons",
		id: "question28",
		"cf-input-placeholder": "Choose one of the above",
		"cf-questions":
			"Henry has achieved 80% of his 15 million naira sales target. How much does he need to sell to meet his target?",
		children: [
			{
				tag: "input",
				type: "radio",
				required: "required",
				value: "1",
				name: "question28",
				"cf-label": "12 million",
			},
			{
				tag: "input",
				type: "radio",
				required: "required",
				value: "2",
				name: "question28",
				"cf-label": "3 million",
			},
			{
				tag: "input",
				type: "radio",
				required: "required",
				value: "3",
				name: "question28",
				"cf-label": "8 million",
			},
			{
				tag: "input",
				type: "radio",
				required: "required",
				value: "4",
				name: "question28",
				"cf-label": "4 million",
			},
		],
	},
];

export default questions;
